In [4]:
import pandas as pd

#data setini yukleme  df(data frame)
df= pd.read_csv("e_ticaret_veri_seti.csv")
df.head()  #df.head() verinin ilk 5 satirini yazdirir.

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,49.9,Kredi Kartı,Yeni,3.0,5.0,Hayır,0.220,443.68
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,29.9,Banka Kartı,VIP,4.0,1.0,Hayır,0.361,2685.17
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,29.9,Kredi Kartı,Mevcut,6.0,2.0,Hayır,0.348,304.47
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,49.9,Kapıda Ödeme,Yeni,3.0,5.0,Hayır,0.250,1023.80
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,39.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.280,2439.03

In [5]:
df.tail() #verinin son 5 satirini yazdirir.

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
1423,SIP101093,MUS1187,2024-06-08 20:42:00,İstanbul,Marmara,Spor,Yoga Matı,1,772.23,0.00,29.9,Kredi Kartı,Mevcut,3.0,2.0,Hayır,0.275,802.13
1424,SIP101193,MUS1297,2025-11-06 08:17:00,Gaziantep,Güneydoğu Anadolu,Spor,Suluk,2,187.03,0.00,59.9,Kredi Kartı,Yeni,2.0,4.0,Evet,0.243,433.96
1425,SIP101210,MUS1122,2025-03-07 09:07:00,NaN,Marmara,Elektronik,Webcam,4,894.47,0.10,49.9,Kredi Kartı,Mevcut,3.0,5.0,Hayır,0.355,3269.99
1426,SIP101060,MUS1189,2025-04-19 21:52:00,Kocaeli,Marmara,Kitap,Veri Bilimi 101,2,248.55,0.05,59.9,banka karti,Yeni,4.0,3.0,Hayır,0.373,532.14
1427,SIP100642,MUS1289,2024-09-22 16:36:00,Ankara,İç Anadolu,Kozmetik,Güneş Kremi,1,424.84,0.20,0.0,Dijital Cüzdan,Yeni,2.0,4.0,Hayır,0.317,339.87

In [6]:
df.shape # (satir,sutun)

(1428, 18)

In [7]:
#boyut ve sutun kontrol et.
satir_sayisi=df.shape[0]
satir_sayisi #1428

1428

In [8]:
sutun_sayisi=df.shape[1]
sutun_sayisi #18

18

In [9]:
#sutun isimleri
for i, sutun in enumerate(df.columns,start=1):
    print(f"{i}.{sutun}")

1.siparis_id
2.musteri_id
3.siparis_tarihi
4.sehir
5.bolge
6.kategori
7.urun_adi
8.adet
9.birim_fiyat
10.indirim_orani
11.kargo_ucreti
12.odeme_turu
13.musteri_tipi
14.teslimat_gunu
15.musteri_puani
16.iade_durumu
17.kar_marji_orani
18.toplam_tutar

In [10]:
#4.veri setinin genel bilgilerini inceleme
df.info() #sutun isimlerini, veri tiplerini ve missing value bilgisi veir

<class 'pandas.DataFrame'>
RangeIndex: 1428 entries, 0 to 1427
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   siparis_id       1428 non-null   str
 1   musteri_id       1428 non-null   str
 2   siparis_tarihi   1428 non-null   str
 3   sehir            1403 non-null   str
 4   bolge            1428 non-null   str
 5   kategori         1428 non-null   str
 6   urun_adi         1428 non-null   str
 7   adet             1428 non-null   int64
 8   birim_fiyat      1428 non-null   float64
 9   indirim_orani    1412 non-null   float64
 10  kargo_ucreti     1428 non-null   float64
 11  odeme_turu       1393 non-null   str
 12  musteri_tipi     1386 non-null   str
 13  teslimat_gunu    1400 non-null   float64
 14  musteri_puani    1372 non-null   float64
 15  iade_durumu      1428 non-null   str
 16  kar_marji_orani  1428 non-null   float64
 17  toplam_tutar     1428 non-null   float64
dtypes: float64(7), int64(1), str(10)
memory usage: 200.9 KB

In [11]:
df.describe() #veri setinin istatistiksel bilgilerini verir.

,adet,birim_fiyat,indirim_orani,kargo_ucreti,teslimat_gunu,musteri_puani,kar_marji_orani,toplam_tutar
count,1428.000000,1428.000000,1412.000000,1428.000000,1400.000000,1372.000000,1428.000000,1428.000000
mean,2.136555,658.477654,0.052054,39.725140,3.370714,4.002187,0.302799,1370.590336
std,2.015770,1042.414639,0.060115,14.185017,1.825990,1.096707,0.069795,2961.689500
min,1.000000,93.110000,0.000000,0.000000,1.000000,0.000000,0.180000,89.680000
25%,1.000000,199.185000,0.000000,29.900000,2.000000,3.000000,0.244750,323.855000
50%,2.000000,287.120000,0.050000,39.900000,3.000000,4.000000,0.305000,669.135000
75%,3.000000,819.177500,0.100000,49.900000,4.000000,5.000000,0.362000,1390.950000
max,38.000000,18145.230000,0.200000,59.900000,31.000000,7.000000,0.420000,63870.200000

In [12]:
#6.Veri tiplerini kontrol etme
df.dtypes #veri tiplerini verir.

siparis_id             str
musteri_id             str
siparis_tarihi         str
sehir                  str
bolge                  str
kategori               str
urun_adi               str
adet                 int64
birim_fiyat        float64
indirim_orani      float64
kargo_ucreti       float64
odeme_turu             str
musteri_tipi           str
teslimat_gunu      float64
musteri_puani      float64
iade_durumu            str
kar_marji_orani    float64
toplam_tutar       float64
dtype: object

In [13]:
#7. sayisal ve kategorik suutnlarin ayrilmasi
#sayisal: float64,int64
#kategorik: object(string)
sayisal_sutunlar= df.select_dtypes(include=["float64","int64"]).columns
sayisal_sutunlar

Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='str')

In [14]:
kategorik_sutunlar=df.select_dtypes(include=["object"]).columns

C:\Users\Hakmar\AppData\Local\Temp\ipykernel_7220\2108111547.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  kategorik_sutunlar=df.select_dtypes(include=["object"]).columns

In [15]:
#8 benzersiz deger syailarıinin verilemsi(uniqie)
for sutun in df.columns:
    print(f"{sutun}: {df[sutun].nunique()}")

siparis_id: 1400
musteri_id: 422
siparis_tarihi: 1398
sehir: 19
bolge: 6
kategori: 15
urun_adi: 30
adet: 10
birim_fiyat: 1381
indirim_orani: 5
kargo_ucreti: 5
odeme_turu: 12
musteri_tipi: 7
teslimat_gunu: 11
musteri_puani: 8
iade_durumu: 2
kar_marji_orani: 241
toplam_tutar: 1397

KAYIP VERİ(MISSING VALUE)
adimlar: 1.ver seti yukleme,eksik verileri tespit etme ,oranları hesaplama, içerensatırları incele,eksik verileri sil, sayısal eksik verileri ort med ,mod ile doldur.Kategorik eksik verileri sabit deger ile doldur. güncel veri setini oluştur ksydet

In [16]:
import pandas as pd
df=pd.read_csv("e_ticaret_veri_seti.csv")

In [17]:
df.isnull().sum() #kac tane eksik veri olduugnu soyler

siparis_id          0
musteri_id          0
siparis_tarihi      0
sehir              25
bolge               0
kategori            0
urun_adi            0
adet                0
birim_fiyat         0
indirim_orani      16
kargo_ucreti        0
odeme_turu         35
musteri_tipi       42
teslimat_gunu      28
musteri_puani      56
iade_durumu         0
kar_marji_orani     0
toplam_tutar        0
dtype: int64

In [18]:
#3. eksik veri ornalrını hesapla
eksik_sayilar=df.isnull().sum()
eksik_oranlar=eksik_sayilar/len(df)*100
eksik_oranlar

siparis_id         0.000000
musteri_id         0.000000
siparis_tarihi     0.000000
sehir              1.750700
bolge              0.000000
kategori           0.000000
urun_adi           0.000000
adet               0.000000
birim_fiyat        0.000000
indirim_orani      1.120448
kargo_ucreti       0.000000
odeme_turu         2.450980
musteri_tipi       2.941176
teslimat_gunu      1.960784
musteri_puani      3.921569
iade_durumu        0.000000
kar_marji_orani    0.000000
toplam_tutar       0.000000
dtype: float64

In [19]:
#4. eksik veri olan satıları incele
eksik_veri_olan_satirlar=df[df.isnull().any(axis=1)]
eksik_veri_olan_satirlar.head(10)

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
19,SIP100677,MUS1148,2024-07-11 16:24:00,Adana,Akdeniz,Spor,Dambıl Seti,4,1517.65,0.0,29.9,Kapıda Ödeme,Mevcut,3.0,NaN,Hayır,0.311,6100.50
33,SIP101126,MUS1406,2024-09-11 20:05:00,Mersin,Akdeniz,Elektronik,Bluetooth Hoparlör,1,1159.89,0.1,39.9,Kredi Kartı,NaN,2.0,4.0,Hayır,0.204,1083.80
50,SIP101040,MUS1386,2025-04-01 09:30:00,Trabzon,Karadeniz,Spor,Dambıl Seti,1,1554.15,0.0,49.9,Banka Kartı,NaN,4.0,5.0,Hayır,0.217,1604.05
60,SIP100890,MUS1271,2024-11-07 19:47:00,İzmir,Ege,Kitap,Girişimcilik,4,216.38,NaN,49.9,Kredi Kartı,Yeni,1.0,3.0,Hayır,0.199,915.42
61,SIP101317,MUS1060,2024-09-05 20:49:00,NaN,Akdeniz,Ev ve Yaşam,Saklama Kutusu,1,233.63,0.1,29.9,Dijital Cüzdan,Yeni,5.0,2.0,Hayır,0.385,240.17
70,SIP100715,MUS1033,2024-11-10 21:50:00,İstanbul,Marmara,Ev ve Yaşam,Termos,1,552.05,0.0,39.9,NaN,Mevcut,2.0,3.0,Hayır,0.185,591.95
82,SIP100807,MUS1431,2025-01-07 14:12:00,Ankara,İç Anadolu,Kozmetik,Güneş Kremi,1,451.28,0.0,49.9,Kredi Kartı,NaN,4.0,5.0,Hayır,0.315,501.18
84,SIP100679,MUS1310,2024-05-20 18:51:00,İzmir,Ege,Ev ve Yaşam,Termos,2,477.62,0.0,49.9,Kredi Kartı,Mevcut,NaN,4.0,Hayır,0.323,1005.14
86,SIP101071,MUS1131,2024-09-18 12:24:00,NaN,İç Anadolu,Elektronik,Powerbank,1,816.74,0.0,39.9,Banka Kartı,Yeni,3.0,5.0,Hayır,0.301,856.64
92,SIP101366,MUS1347,2025-03-04 14:00:00,Bursa,Marmara,Ev ve Yaşam,Organizer,1,272.40,0.0,29.9,Kredi Kartı,Mevcut,1.0,NaN,Hayır,0.212,302.30

In [20]:
#eksik verileri silme : df.dropna

In [21]:
df_silinen= df.dropna()
df_silinen.shape

(1239, 18)

In [22]:
#6. sayısal eksik verilerin ortalama ile doldurulması:
df_ortalama =df.copy()
sayisal_sutunlar=df_ortalama.select_dtypes(include=["int64","float64"]).columns
sayisal_sutunlar

Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='str')

In [23]:
for sutun in sayisal_sutunlar:
    df_ortalama[sutun]= df_ortalama[sutun].fillna(df_ortalama[sutun].mean())

In [24]:
df_ortalama[sayisal_sutunlar].isnull().sum() #eksik veri kalmadı mı kontrol etme (null deger bos deger demek)

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [25]:
#7. kategorik eksik verilerin medyan ile doldurulması:
df_medyan =df.copy()
for sutun in sayisal_sutunlar:
    df_medyan[sutun]= df_medyan[sutun].fillna(df_medyan[sutun].median())
    df_medyan[sayisal_sutunlar].isnull().sum()

In [26]:
df_ortalama[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [27]:
#sayisal eksik verileri mod ile doldurma
df_mod_sayisal= df.copy()
for sutun in sayisal_sutunlar:
  mod_degeri=df_mod_sayisal[sutun].mode()
  df_mod_sayisal[sutun]= df_mod_sayisal[sutun].fillna(df_mod_sayisal[sutun].median() )
  df_mod_sayisal[sayisal_sutunlar].isnull().sum()

In [28]:
df_ortalama[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [29]:
#5.eksik verileri silme
df_silinen= df.dropna() #dropna ile eksik degerli verileri çıkarttık
df_silinen.shape # eksik verileri silince satır sayısı azaldı mı kontrol etme

(1239, 18)

In [30]:
#6 sayisal eksik verilerin ortalama ile doldurulması.
df_ortalama =df.copy()
sayisal_sutunlar=df_ortalama.select_dtypes(include=["int64","float64"]).columns
sayisal_sutunlar

Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='str')

In [31]:
for sutun in sayisal_sutunlar:
    df_ortalama[sutun]= df_ortalama[sutun].fillna(df_ortalama[sutun].mean())

In [32]:
df_ortalama[sayisal_sutunlar].isnull().sum() #eksik veri kalmadı mı kontrol etme

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

VERİ TİPLERİ VE DONUŞUMLER

In [33]:
import pandas as pd

In [34]:
#veri setini yukleme  df(data frame)
df= pd.read_csv("e_ticaret_veri_seti_eksik_veriler_duzenlendi.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'e_ticaret_veri_seti_eksik_veriler_duzenlendi.csv'

In [ ]:
df.dtypes

siparis_id             str
musteri_id             str
siparis_tarihi         str
sehir                  str
bolge                  str
kategori               str
urun_adi               str
adet                 int64
birim_fiyat        float64
indirim_orani      float64
kargo_ucreti       float64
odeme_turu             str
musteri_tipi           str
teslimat_gunu      float64
musteri_puani      float64
iade_durumu            str
kar_marji_orani    float64
toplam_tutar       float64
dtype: object

In [ ]:
sayisal_sutunlar= df.select_dtypes(include=["int64","float64"]).columns.tolist()
sayisal_sutunlar

['adet',
 'birim_fiyat',
 'indirim_orani',
 'kargo_ucreti',
 'teslimat_gunu',
 'musteri_puani',
 'kar_marji_orani',
 'toplam_tutar']

In [ ]:
kategorik_sutunlar= df.select_dtypes(include=["object"]).columns.tolist()
kategorik_sutunlar

C:\Users\User\AppData\Local\Temp\ipykernel_9908\1982026891.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  kategorik_sutunlar= df.select_dtypes(include=["object"]).columns.tolist()

['siparis_id',
 'musteri_id',
 'siparis_tarihi',
 'sehir',
 'bolge',
 'kategori',
 'urun_adi',
 'odeme_turu',
 'musteri_tipi',
 'iade_durumu']

In [ ]:
#4. siparis tarihi sutununu datetime tipine donusturmwj(string -> datetime)
df["siparis_tarihi"] = pd.to_datetime(df["siparis_tarihi"])
df["siparis_tarihi"].dtype
#veya böyle check et
df.dtypes

siparis_id                    str
musteri_id                    str
siparis_tarihi     datetime64[us]
sehir                         str
bolge                         str
kategori                      str
urun_adi                      str
adet                        int64
birim_fiyat               float64
indirim_orani             float64
kargo_ucreti              float64
odeme_turu                    str
musteri_tipi                  str
teslimat_gunu             float64
musteri_puani             float64
iade_durumu                   str
kar_marji_orani           float64
toplam_tutar              float64
dtype: object

In [ ]:
#5. tarih sutunundan yeni özelliklerin üretilmesi
#zaman bazlı analizlerde  yıl,ay gün vs üretiyoruz ekliyoruz.
df["siparis_yili"]= df["siparis_tarihi"].dt.year
df["siparis_ayi"]= df["siparis_tarihi"].dt.month
df["siparis_gunu"]= df["siparis_tarihi"].dt.day
df["haftanin_gunu"]= df["siparis_tarihi"].dt.day_name()
df.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,...,Yeni,3.0,5.0,Hayır,0.220,443.68,2024,1,13,Saturday
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,...,VIP,4.0,1.0,Hayır,0.361,2685.17,2025,3,17,Monday
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,...,Mevcut,6.0,2.0,Hayır,0.348,304.47,2025,6,3,Tuesday
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,...,Yeni,3.0,5.0,Hayır,0.250,1023.80,2024,8,10,Saturday
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,...,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday

In [ ]:
#6 kategorik sutunları category tipine dünüştürme
kategorik_donusum_sutunlari = [
    "sehir",
    "kategori",
    "urun_adi",
    "odeme_turu"
    "musteri_tipi",
    "haftanin_gunu"
  
]

In [ ]:
df.dtypes

siparis_id                    str
musteri_id                    str
siparis_tarihi     datetime64[us]
sehir                         str
bolge                         str
kategori                      str
urun_adi                      str
adet                        int64
birim_fiyat               float64
indirim_orani             float64
kargo_ucreti              float64
odeme_turu                    str
musteri_tipi                  str
teslimat_gunu             float64
musteri_puani             float64
iade_durumu                   str
kar_marji_orani           float64
toplam_tutar              float64
siparis_yili                int32
siparis_ayi                 int32
siparis_gunu                int32
haftanin_gunu                 str
dtype: object

In [ ]:
#8 güncellenmiş veri setini kaydedelim.
df.to_csv("e_ticaret_veri_seti_eksik_veriler_duzenlendi.csv", index=False)

Tekrarlayan ve Tutarsız Kayıtlar:

In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv("e_ticaret_veri_seti_veri_tipleri_duzenlendi.csv")
df.shape

(1428, 22)

TEKRARLAYAN VE TUTARSIZ KAYITLAR

büyük küçük harfler, boşluk, sesli sessiz ahrf farkı tekrar hatası verbeilir. dikat ett!!!!!!!!!!

In [ ]:
#tekrarlayan kayıtları tespit et (duplicate yapar)
tekrarlayan_kayitlar=df[df.duplicated()]
len(tekrarlayan_kayitlar)

28

In [ ]:
#3. tekrarlayan kayıtları incele
tekrarlayan_kayitlar.head(5)

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
174,SIP100479,MUS1099,2025-06-10 20:32:00,İstanbul,Marmara,Kozmetik,Güneş Kremi,3,455.19,0.00,...,Yeni,1.0,5.0,Hayır,0.200,1415.47,2025,6,10,Tuesday
315,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,...,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday
324,SIP100533,MUS1128,2024-11-19 14:22:00,Trabzon,Karadeniz,Kitap,Python Notları,2,225.82,0.00,...,Yeni,4.0,5.0,Hayır,0.234,491.54,2024,11,19,Tuesday
613,SIP100725,MUS1146,2025-05-24 10:10:00,Kocaeli,Marmara,Kitap,Zaman Yönetimi,2,154.18,0.05,...,Yeni,3.0,5.0,Hayır,0.385,342.84,2025,5,24,Saturday
637,SIP100940,MUS1032,2025-03-25 20:06:00,Samsun,Karadeniz,Kozmetik,Serum,1,507.46,0.15,...,Mevcut,3.0,4.0,Evet,0.402,471.24,2025,3,25,Tuesday

In [ ]:
#4 tekrarlayan kayıtları silme
df =df.drop_duplicates()
df.shape

(1400, 22)

In [ ]:
#5 tutarsız degerlerin incelenmesi
df["sehir"].unique() #istanbul,ankara, gaziantep ,izmir tekrarlıyo sıkıntı

<StringArray>
[ 'İstanbul', 'Gaziantep',   'Kayseri',   'Antalya',     'Konya',    'Ankara',
     'Bursa',   'Trabzon',     'Adana',    'Mersin',   'Kocaeli',     'İzmir',
 'Eskişehir',    'Samsun',  'istanbul',    'ankara',  'Istanbul', 'gaziantep',
     'Izmir']
Length: 19, dtype: str

In [ ]:
df["kategori"].unique() #elektronik(boşluk var), kitap,kozmetik, ev ve yasam vs sıkıntıı

<StringArray>
[   'Kozmetik',        'Spor',       'Kitap',  'Elektronik',        'Ofis',
        'ofis', 'Ev ve Yaşam', 'Elektronik ',        'spor',    'kozmetık',
 'ev ve yaşam',       'kitap',   'Kozmetik ',  'elektronik',    'Ev&Yaşam']
Length: 15, dtype: str

In [ ]:
df["odeme_turu"].unique() #banka kartı,kapıda odeme,havale,dijital cüzdan sıkıntı
#basta odeme turu:12 yazdırmıştık demek ki yanlışmış yani hatalı veriyle analiz yapmışız. Bu yüzden veri tiplerini düzenledik ve kaydettik. Artık sorun yok.

<StringArray>
[   'Kredi Kartı',    'Banka Kartı',   'Kapıda Ödeme', 'Dijital Cüzdan',
     'Havale/EFT',           'Kart',    'kredi kartı', 'dijital cüzdan',
            'eft',    'banka karti',   'Kapida Odeme',         'Havale']
Length: 12, dtype: str

In [ ]:
df["musteri_tipi"].unique() #vip,mevcut,yeni hatalı

<StringArray>
['Yeni', 'VIP', 'Mevcut', 'yeni', 'Vip', 'mevcut', 'vip']
Length: 7, dtype: str

In [ ]:
#yardimci fonskiyon:metinleri nromalize edelim.
#buyuk kucuk harf donusum,bosluklari kaldirma, noktalama isaretlerini kaldirma, turkce karakterleri duzeltme
def metin_normalize_et(series):

    return(
        series.astype(str) #veri tipini stringe donustur
        .str.strip() #bas ve sondaki bosluklari kaldir
        .str.lower() #buyuk harfleri kucuk harfe donustur
        .str.replace("ı","i") #turkce karakterleri duzeltme
        .str.replace("ş","s") #turkce karakterleri duzeltme
        .str.replace("ğ","g") #turkce karakterleri duzeltme
        .str.replace("ü","u") #turkce karakterleri duzeltme
        .str.replace("ö","o") #turkce karakterleri duzeltme
    
    )

In [ ]:
#6 sehir sutunundaki hatali verileri düzeltme:
df["sehir"]= metin_normalize_et(df["sehir"])
df["sehir"].unique()  #bu kodla beraber sehir saririrndaki veriler düzeldi.

<StringArray>
['i̇stanbul', 'gaziantep',   'kayseri',   'antalya',     'konya',    'ankara',
     'bursa',   'trabzon',     'adana',    'mersin',   'kocaeli',    'i̇zmir',
 'eskisehir',    'samsun',  'istanbul',     'izmir']
Length: 16, dtype: str

In [ ]:
sehir_duzeltme_haritasi= { #normalde bunu yapmana gerek yok ama türkçe kullnamak istiyosan böyle yapablisn
    "istanbul":"İstanbul",
    "ankara":"Ankara",  
    "izmir":"İzmir",
    "antalya": "Antalya",
    "konya": "Konya",
    "bursa": "Bursa",
    "adana": "Adana",
    "gaziantep": "Gaziantep",
    "mersin": "Mersin",
    "kayseri": "Kayseri",
    "eskisehir": "Eskişehir",
    "samsun": "Samsun",
    "trabzon": "Trabzon",
    "kocaeli": "Kocaeli"
}
df["sehir"]= df["sehir"].replace(sehir_duzeltme_haritasi)
df["sehir"].unique() #sehir sutunundaki hatali veriler duzeltilmis oldu.

<StringArray>
['i̇stanbul', 'Gaziantep',   'Kayseri',   'Antalya',     'Konya',    'Ankara',
     'Bursa',   'Trabzon',     'Adana',    'Mersin',   'Kocaeli',    'i̇zmir',
 'Eskişehir',    'Samsun',  'İstanbul',     'İzmir']
Length: 16, dtype: str

In [ ]:
#7.kategori sutunda tutarsız degeleri duzeltme
df["kategori"] =metin_normalize_et(df["kategori"])
df["kategori"].unique()  #ev ve yasam sıkıntılı

<StringArray>
['kozmetik', 'spor', 'kitap', 'elektronik', 'ofis', 'ev ve yasam', 'ev&yasam']
Length: 7, dtype: str

In [ ]:
kategori_duzeltme_haritasi = {
    "elektronik": "Elektronik",
    "kitap": "Kitap",
    "kozmetik": "Kozmetik",
    "kozmetık": "Kozmetik",
    "spor": "Spor",
    "ev yasam": "Ev Yaşam",
    "ev ve yasam": "Ev Yaşam",
    "ev&yasam": "Ev Yaşam",
    "ofis": "Ofis"
}

In [ ]:
df["kategori"]= df["kategori"].replace(kategori_duzeltme_haritasi)
df["kategori"].unique()

<StringArray>
['Kozmetik', 'Spor', 'Kitap', 'Elektronik', 'Ofis', 'Ev Yaşam']
Length: 6, dtype: str

In [ ]:
#8 odeme turu sutunundaki tutarsızları kaldrıma
df["odeme_turu"] = metin_normalize_et(df["odeme_turu"])
df["odeme_turu"].unique() #havale,eft sıkıntı, kart

<StringArray>
[   'kredi karti',    'banka karti',   'kapida odeme', 'dijital cuzdan',
     'havale/eft',           'kart',            'eft',         'havale']
Length: 8, dtype: str

In [ ]:
odeme_turu_duzeltme_haritasi = {
    "kredi karti": "Kredi Kartı",
    "kart": "Kredi Kartı",
    "banka karti": "Banka Kartı",
    "dijital cuzdan": "Dijital Cüzdan",
    "kapida odeme": "Kapıda Ödeme",
    "havale": "Havale/EFT",
    "eft": "Havale/EFT",
    "havale/eft": "Havale/EFT"
}
df["odeme_turu"] = df["odeme_turu"].replace(odeme_turu_duzeltme_haritasi)
df["odeme_turu"].unique()

<StringArray>
['Kredi Kartı', 'Banka Kartı', 'Kapıda Ödeme', 'Dijital Cüzdan', 'Havale/EFT']
Length: 5, dtype: str

In [ ]:
#9 museti sutunundaki hatalrı duzeltme:
df["musteri_tipi"] = metin_normalize_et(df["musteri_tipi"])
df["musteri_tipi"].unique()

<StringArray>
['yeni', 'vip', 'mevcut']
Length: 3, dtype: str

In [ ]:
musteri_tipi_duzeltme_haritasi= {
    "mevcut": "Mevcut",
    "yeni":"Yeni",
    "vip": "Vip",

}
df["musteri_tipi"]= df["musteri_tipi"].replace(musteri_tipi_duzeltme_haritasi)
df["musteri_tipi"].unique()

<StringArray>
['Yeni', 'Vip', 'Mevcut']
Length: 3, dtype: str

In [ ]:
df["musteri_tipi"].value_counts() #kac tane olduklarını ogreniriz.

musteri_tipi
Mevcut    716
Yeni      520
Vip       164
Name: count, dtype: int64

In [ ]:
#10. mantıksal olarak hatalı kayıtları inceleme:
#negatif ya da anlamsız degerler bazı kayıtlarda veri kalitesini düşürebilir

hatali_kayitlar =df [
    (df["adet"] <=0) | #veya demek(bu sartlardan herhangibirini ihlal eden hatalı satrıları yakal ve hatalı_kayitlar listesine at
    
    (df["toplam_tutar"] <=0) |
    (df["birim_fiyat"] <=0)|
    (df["teslimat_gunu"] <0 )|
    (df["musteri_puani"] <0 )|
    (df["musteri_puani"] >5) 
]
len(hatali_kayitlar)

0

In [ ]:
pd.set_option("display.max_columns",None) # butun sutunları gosteirr normlade bazıları görünmüyor
hatali_kayitlar #musteri puanları sıkıntılı

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
609,SIP100095,MUS1165,2025-10-12 21:31:00,i̇stanbul,Marmara,Kozmetik,Şampuan,2,190.17,0.10,0.0,Dijital Cüzdan,Mevcut,3.0,6.0,Hayır,0.416,342.31,2025,10,12,Sunday
1008,SIP101290,MUS1225,2024-01-16 21:46:00,Kocaeli,Marmara,Kozmetik,Yüz Temizleme Jeli,2,303.82,0.05,29.9,Kredi Kartı,Yeni,5.0,7.0,Evet,0.287,607.16,2024,1,16,Tuesday

In [ ]:
#11. mantıksal verileri duzeltelim.
df=df [
    (df["adet"] >0) & #ve isareti ile yap (bu şartları aynı anda saglayan satırları df'i bunlarla güncelle)
    (df["toplam_tutar"] >0) &
    (df["birim_fiyat"] >=0)&
    (df["teslimat_gunu"] >=0 )&
    (df["musteri_puani"] >=0 )&
    (df["musteri_puani"] <=5) 
]
df.shape

(1398, 22)

In [ ]:
#12 güncellenmiş verileri kaydet: yani dosyalara ayrıyaten sen kaydediyosun 
df.to_csv("e_ticaret_veri_seti_tekrarlayan_kayitlar_duzenlendi.csv")

AYKIRI DEGERLER(OUTLIERS)
Veri setini yükle
Sayısal sütunları belirle
Sayısal sütunların özet istatistiklerini hesapla
IQR ile aykırı değer sınırlarını hesapla
Aykırı değer içeren kayıtları tespit etmek
Aykırı değer sayılarını sütun bazında incelemek
Aykırı değer içeren kayıtları veri setinden temizlemek
Temizlenmiş veri setini kaydetmek

In [ ]:
import pandas as pd
#1.veri setini yuklemek
df =pd.read_csv("e_ticaret_veri_seti_tekrarlayan_kayitlar_duzenlendi.csv")

In [ ]:
#2. sayisal sutunların belirlenmesi:
sayisal_sutunlar= df.select_dtypes(include=["int64","float64"]).columns.tolist()
sayisal_sutunlar

['Unnamed: 0',
 'adet',
 'birim_fiyat',
 'indirim_orani',
 'kargo_ucreti',
 'teslimat_gunu',
 'musteri_puani',
 'kar_marji_orani',
 'toplam_tutar',
 'siparis_yili',
 'siparis_ayi',
 'siparis_gunu']

In [36]:
#3. sayisal sutunların özet isttaitiklerini inceleyim:
df[sayisal_sutunlar].describe()

,adet,birim_fiyat,indirim_orani,kargo_ucreti,teslimat_gunu,musteri_puani,kar_marji_orani,toplam_tutar
count,1428.000000,1428.000000,1412.000000,1428.000000,1400.000000,1372.000000,1428.000000,1428.000000
mean,2.136555,658.477654,0.052054,39.725140,3.370714,4.002187,0.302799,1370.590336
std,2.015770,1042.414639,0.060115,14.185017,1.825990,1.096707,0.069795,2961.689500
min,1.000000,93.110000,0.000000,0.000000,1.000000,0.000000,0.180000,89.680000
25%,1.000000,199.185000,0.000000,29.900000,2.000000,3.000000,0.244750,323.855000
50%,2.000000,287.120000,0.050000,39.900000,3.000000,4.000000,0.305000,669.135000
75%,3.000000,819.177500,0.100000,49.900000,4.000000,5.000000,0.362000,1390.950000
max,38.000000,18145.230000,0.200000,59.900000,31.000000,7.000000,0.420000,63870.200000

In [ ]:
"""birim_fiyat
IQR= Q3(%75)-Q1(%25)
   =817-198= 619
   üst sınır= Q3+k*IQR  yani 1436
   alt sınır=Q1-k*IQR   yani -421 !! k yı genel olarak 1 alırız.
   outlier=ust ve allt sinir sisinda kalan ornekler
k=1


"""

'birim_fiyat\nIQR= Q3(%75)-Q1(%25)\n   =817-198= 619\n   üst sınır= Q3+k*IQR  yani 1436\n   alt sınır=Q1-k*IQR   yani -421 !! k yı genel olarak 1 alırız.\n   outlier=ust ve allt sinir sisinda kalan ornekler\nk=1\n\n\n'

In [37]:
#4. IQR ile aykırı deger sınırlarını hesaplama
aykiri_sinirlar = {}

for sutun in sayisal_sutunlar:

    q1= df[sutun].quantile(0.25)
    q3=df[sutun].quantile(0.75)

    iqr= q3-q1
    alt_sinir= q1- 1.5*iqr
    ust_sinir= q3+ 1.5*iqr

    aykiri_sinirlar[sutun] = {
        "q1":q1,
        "q3":q3,
        "iqr":iqr,
        "alt_sinir":alt_sinir,
        "ust_sinir":ust_sinir
 }

In [ ]:
aykiri_sinirlar #ıqr 619 cıktı yani dogru diğerleri farklı olabilir

{'Unnamed: 0': {'q1': np.float64(352.25),
  'q3': np.float64(1064.75),
  'iqr': np.float64(712.5),
  'alt_sinir': np.float64(-716.5),
  'ust_sinir': np.float64(2133.5)},
 'adet': {'q1': np.float64(1.0),
  'q3': np.float64(3.0),
  'iqr': np.float64(2.0),
  'alt_sinir': np.float64(-2.0),
  'ust_sinir': np.float64(6.0)},
 'birim_fiyat': {'q1': np.float64(198.85500000000002),
  'q3': np.float64(817.335),
  'iqr': np.float64(618.48),
  'alt_sinir': np.float64(-728.865),
  'ust_sinir': np.float64(1745.055)},
 'indirim_orani': {'q1': np.float64(0.0),
  'q3': np.float64(0.1),
  'iqr': np.float64(0.1),
  'alt_sinir': np.float64(-0.15000000000000002),
  'ust_sinir': np.float64(0.25)},
 'kargo_ucreti': {'q1': np.float64(29.9),
  'q3': np.float64(49.9),
  'iqr': np.float64(20.0),
  'alt_sinir': np.float64(-0.10000000000000142),
  'ust_sinir': np.float64(79.9)},
 'teslimat_gunu': {'q1': np.float64(2.0),
  'q3': np.float64(4.0),
  'iqr': np.float64(2.0),
  'alt_sinir': np.float64(-1.0),
  'ust_sinir': np.float64(7.0)},
 'musteri_puani': {'q1': np.float64(4.0),
  'q3': np.float64(5.0),
  'iqr': np.float64(1.0),
  'alt_sinir': np.float64(2.5),
  'ust_sinir': np.float64(6.5)},
 'kar_marji_orani': {'q1': np.float64(0.24325),
  'q3': np.float64(0.362),
  'iqr': np.float64(0.11875),
  'alt_sinir': np.float64(0.06512500000000002),
  'ust_sinir': np.float64(0.540125)},
 'toplam_tutar': {'q1': np.float64(327.19),
  'q3': np.float64(1393.25),
  'iqr': np.float64(1066.06),
  'alt_sinir': np.float64(-1271.8999999999999),
  'ust_sinir': np.float64(2992.34)},
 'siparis_yili': {'q1': np.float64(2024.0),
  'q3': np.float64(2025.0),
  'iqr': np.float64(1.0),
  'alt_sinir': np.float64(2022.5),
  'ust_sinir': np.float64(2026.5)},
 'siparis_ayi': {'q1': np.float64(3.0),
  'q3': np.float64(9.0),
  'iqr': np.float64(6.0),
  'alt_sinir': np.float64(-6.0),
  'ust_sinir': np.float64(18.0)},
 'siparis_gunu': {'q1': np.float64(8.0),
  'q3': np.float64(23.0),
  'iqr': np.float64(15.0),
  'alt_sinir': np.float64(-14.5),
  'ust_sinir': np.float64(45.5)}}

In [38]:
#5 aykiri deger iceren kayitlari tespit et
aykiri_maskesi= pd.Series(False,index =df.index) #ilk basta tum satirlar False yani aykırı deger yok. bu yüzden maske deriz.kontorl listesi oluşturduk yani.

for sutun in sayisal_sutunlar:
    alt_sinir=aykiri_sinirlar[sutun]["alt_sinir"] #aykirisinirlar sozlugunden o sutuna ait hesaplanmıs alt sınıır cekiyor
    ust_sinir=aykiri_sinirlar[sutun]["ust_sinir"]

    sutun_maskesi= (df[sutun] <alt_sinir) | (df[sutun] > ust_sinir) #o anki sutun icin alt sınırdan kucuk mu    or   ust sınırdan buyuk mu kontrolu
    #Sadece o sütunda sınırların dışında kalan aykırı değerler için True, normal olanlar için False üreten geçici bir maske elde eder.
    aykiri_maskesi= aykiri_maskesi | sutun_maskesi #Ana maskeyi (aykiri_maskesi), o sütun için bulduğu yeni maske (sutun_maskesi) ile | (VEYA) işlemine sokup güncelliyor.
    #Mantığı: Bir satır daha önceki sütunlarda aykırı bulunmuşsa (True), bu yeni sütunda aykırı olmasa bile True kalmaya devam eder. Eğer ilk defa bu sütunda bir aykırı değer yakalandıysa, o satır da artık True olarak işaretlenir.
    #True olan satırlar: Herhangi bir sayısal sütununda en az bir tane aykırı değer (uç değer) barındıran satırlardır.

In [ ]:
aykiri_kayitlar= df[aykiri_maskesi]
aykiri_kayitlar  #toplam 303 tane aykiri kayıdımız var
#1.5 degerini artırsak  aykırı deger sayısı azalacak, aykiri degerlere bakarak sınırın içinde mi deigl mi diye bakmalısın

,Unnamed: 0,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
1,1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,...,Vip,4.0,1.0,Hayır,0.361,2685.17,2025,3,17,Monday
2,2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,...,Mevcut,6.0,2.0,Hayır,0.348,304.47,2025,6,3,Tuesday
6,6,SIP101351,MUS1011,2025-02-27 11:35:00,i̇stanbul,Marmara,Ofis,Mouse Pad,3,169.47,...,Vip,3.0,2.0,Evet,0.382,512.89,2025,2,27,Thursday
7,7,SIP101172,MUS1357,2024-07-22 13:26:00,Ankara,İç Anadolu,Ofis,Mekanik Klavye,3,2344.47,...,Mevcut,3.0,4.0,Hayır,0.312,7093.31,2024,7,22,Monday
8,8,SIP100779,MUS1354,2025-12-05 11:19:00,i̇stanbul,Marmara,Kitap,Python Notları,4,219.14,...,Yeni,18.0,5.0,Evet,0.408,906.46,2025,12,5,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1387,1416,SIP100177,MUS1075,2024-01-29 13:59:00,Trabzon,Karadeniz,Ofis,Mekanik Klavye,3,2169.51,...,Mevcut,1.0,4.0,Hayır,0.273,6548.43,2024,1,29,Monday
1389,1418,SIP100056,MUS1238,2024-04-19 20:27:00,Ankara,İç Anadolu,Kitap,Veri Bilimi 101,2,255.70,...,Mevcut,3.0,2.0,Hayır,0.247,545.73,2024,4,19,Friday
1390,1419,SIP101279,MUS1149,2024-08-24 08:38:00,Ankara,İç Anadolu,Elektronik,Akıllı Saat,4,3074.80,...,Yeni,4.0,5.0,Hayır,0.414,10494.22,2024,8,24,Saturday
1393,1423,SIP101093,MUS1187,2024-06-08 20:42:00,i̇stanbul,Marmara,Spor,Yoga Matı,1,772.23,...,Mevcut,3.0,2.0,Hayır,0.275,802.13,2024,6,8,Saturday
1395,1425,SIP101210,MUS1122,2025-03-07 09:07:00,i̇stanbul,Marmara,Elektronik,Webcam,4,894.47,...,Mevcut,3.0,5.0,Hayır,0.355,3269.99,2025,3,7,Friday

In [39]:
#6. aykiri deger sayilarini sutun bazında incele
for sutun in sayisal_sutunlar:

  alt_sinir = aykiri_sinirlar[sutun]["alt_sinir"]
  ust_sinir = aykiri_sinirlar[sutun]["ust_sinir"]

  aykiri_sayi = ((df[sutun] < alt_sinir) | (df[sutun] > ust_sinir)).sum()
  print(f"{sutun}: {aykiri_sayi}")

adet: 6
birim_fiyat: 93
indirim_orani: 0
kargo_ucreti: 0
teslimat_gunu: 6
musteri_puani: 0
kar_marji_orani: 0
toplam_tutar: 137

In [ ]:
#7 aykırı degerler içeren kayıtları veri setinden temizleme

df_temiz= df[~aykiri_maskesi].copy() #~ bu işaret not anlamıdır maskeyi tersine çevirdik. trueyu false ,falseu true yaptık.
df_temiz.shape          #ayrıca copy yazarak bir kopya oluşturduk yapmasaydık orijinal veri bozulmasın diye hata verirdi.

(1257, 18)

In [41]:
#8. temizlemiş veri setini kaydet (yeni belge olarak),
df_temiz.to_csv("e_ticaret_veri_seti_aykiri_degerler_duzenlendi.csv")